const tokenInput=document.querySelector('#admin-token'),statusEl=document.querySelector('#admin-status'),listEl=document.querySelector('#question-list'),hintEl=document.querySelector('#setup-hint');
let adminToken='',activeStatus='draft',allQuestions=[];
const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
function setStatus(text,kind=''){statusEl.textContent=text;statusEl.className='admin-status '+kind}
function headers(){return {'Authorization':`Bearer ${adminToken}`,'Content-Type':'application/json'}}
async function api(url,options={}){const response=await fetch(url,{...options,headers:{...headers(),...(options.headers||{})}});let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.error||`Permintaan gagal (${response.status})`);return data}
function counts(){for(const status of ['draft','active','rejected'])document.querySelector(`#count-${status}`).textContent=allQuestions.filter(q=>q.status===status).length}
function renderList(){const questions=allQuestions.filter(q=>q.status===activeStatus);counts();if(!questions.length){listEl.innerHTML=`<div class="empty-bank"><span>${activeStatus==='draft'?'🧠':activeStatus==='active'?'🎮':'🗃️'}</span><strong>${activeStatus==='draft'?'Belum ada draft':activeStatus==='active'?'Belum ada soal aktif':'Belum ada soal ditolak'}</strong><p>${activeStatus==='draft'?'Buat beberapa soal lewat Gemini; hasilnya akan menunggu pemeriksaan di sini.':activeStatus==='active'?'Aktifkan soal draft agar bisa muncul di sesi solo.':'Soal yang ditolak akan tersimpan di tab ini.'}</p></div>`;return}
  listEl.innerHTML=questions.map(q=>`<article class="question-card"><div class="question-card-head"><span class="category-tag">${esc(q.category||'Umum')} · ${esc(q.difficulty||'sedang')}</span>${q.isTrap?'<span class="category-tag">⚠ Jebakan</span>':''}<span class="status-chip ${q.status}">${q.status==='draft'?'Draft':q.status==='active'?'Aktif':'Ditolak'}</span></div><h3>${esc(q.question)}</h3><div class="draft-options">${q.options.map((option,i)=>`<div class="draft-option ${i===q.answerIndex?'answer':''}">${'ABCD'[i]}. ${esc(option)} ${i===q.answerIndex?'✓':''}</div>`).join('')}</div><div class="draft-explanation">${esc(q.explanation)}</div><div class="question-meta">Sumber: Gemini ${esc(q.model||'')} · ${new Date(q.createdAt).toLocaleString('id-ID')}</div><div class="question-card-actions">${q.status!=='active'?`<button class="btn btn-success" data-status-action="active" data-id="${esc(q.id)}">✓ Aktifkan</button>`:''}${q.status!=='rejected'?`<button class="btn btn-danger" data-status-action="rejected" data-id="${esc(q.id)}">Tolak</button>`:''}${q.status!=='draft'?`<button class="btn btn-outline" data-status-action="draft" data-id="${esc(q.id)}">Kembalikan ke draft</button>`:''}</div></article>`).join('')}
async function refresh(){if(!adminToken){setStatus('Masukkan token admin untuk mengakses cache.','');return}setStatus('Memuat bank soal…','loading');try{const data=await api('/api/admin/questions');allQuestions=data.questions||[];renderList();setStatus(`${allQuestions.length} soal tersimpan di cache.`,'success');hintEl.hidden=true}catch(error){setStatus(error.message,'error');hintEl.hidden=false;hintEl.textContent=error.message.includes('Token admin')?'Token salah. Periksa secret AI_ADMIN_TOKEN di backend.':'Backend belum siap. Konfigurasikan Cloudflare Pages Functions, binding KV QUESTION_CACHE, dan secret AI_ADMIN_TOKEN. Detail: '+error.message}}
document.querySelector('#admin-form').addEventListener('submit',async event=>{event.preventDefault();adminToken=tokenInput.value.trim();if(!adminToken){setStatus('Masukkan token admin terlebih dahulu.','error');return}const button=document.querySelector('#generate-btn');button.disabled=true;button.textContent='◌ Sedang membuat…';setStatus('Meminta Gemini membuat soal…','loading');hintEl.hidden=true;try{const data=await api('/api/admin/generate',{method:'POST',body:JSON.stringify({category:document.querySelector('#category').value.trim(),difficulty:document.querySelector('#difficulty').value,count:Number(document.querySelector('#count').value)})});allQuestions=[...data.drafts,...allQuestions.filter(question=>!data.drafts.some(draft=>draft.id===question.id))];const suffix=data.skipped?` · ${data.skipped} soal duplikat/tidak valid dilewati`:'';setStatus(`${data.drafts.length} draft berhasil dibuat dengan ${data.model}${suffix}.`,'success');activeStatus='draft';document.querySelectorAll('.bank-tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.status==='draft'));renderList()}catch(error){setStatus(error.message,'error');hintEl.hidden=false;hintEl.textContent='Periksa secret GEMINI_API_KEY, variable GEMINI_MODEL, binding QUESTION_CACHE, dan batas kuota Gemini. Detail: '+error.message}finally{button.disabled=false;button.textContent='✦ Generate soal'}});
document.querySelector('#refresh-btn').addEventListener('click',()=>{adminToken=tokenInput.value.trim();refresh()});
document.querySelector('.bank-tabs').addEventListener('click',event=>{const tab=event.target.closest('[data-status]');if(!tab)return;activeStatus=tab.dataset.status;document.querySelectorAll('.bank-tab').forEach(item=>item.classList.toggle('active',item===tab));renderList()});
listEl.addEventListener('click',async event=>{const button=event.target.closest('[data-status-action]');if(!button)return;button.disabled=true;try{await api('/api/admin/questions',{method:'PATCH',body:JSON.stringify({id:button.dataset.id,status:button.dataset.statusAction})});const item=allQuestions.find(q=>q.id===button.dataset.id);if(item)item.status=button.dataset.statusAction;renderList();setStatus('Status soal diperbarui.','success')}catch(error){button.disabled=false;setStatus(error.message,'error')}});
tokenInput.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();document.querySelector('#generate-btn').click()}});
